/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import Storage from '@aws-amplify/storage';

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:492900ee-4da9-4e2b-8aac-fef27eb7bf7c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yb8ya7OYW",
    "aws_user_pools_web_client_id": "70irarcn411o7qp9qshuhlk5jo",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hznvmg5bwvhslcdb3ybv5e5sw4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_s3_bucket_name": "ingredient-20149581-media"
};


export default awsmobile;

export function SetS3Config(bucket, level){
    Storage.configure({ 
           bucket: bucket,
           level: level,
           region: 'us-east-1',  
           identityPoolId: "us-east-1:492900ee-4da9-4e2b-8aac-fef27eb7bf7c"
        });
 }
